### PR TITLE
Migrate to xml2js

### PR DESCRIPTION
**Pull request by vdel26**
Removing our dependency on libxmljs which was causing many issues when building its native dependencies on certain environments. 
This PR builds on top of https://github.com/3scale/3scale_ws_api_for_nodejs/pull/25 by @picsoung.

A couple of notes:
- xml2js is different to libxmljs in that it has an asynchronous API, so it requires some internal changes
  in the way the response is passed to the user's callback
- introduce es6-promise to make it (hopefully) more readable

### CODE REVIEW

**Comment by mikz** [comment]
Looks pretty good! :+1:

**Comment by mikz** [comment]
@vdel26 imo this would deserve a changelog entry so bad, that we should start a changelog for this :) and some big version bump.

**Comment by vdel26** [comment]
@mikz I agree. I updated the version from 0.6.2 to 0.7.0. I think it should be enough because this is not a major external change, but what do you think? 
I will start a changelog now and also update the readme, which I should have done but I forgot.

**Comment by mikz** [comment]
I did small change to the readme in https://github.com/3scale/3scale_ws_api_for_nodejs/pull/32

Good job! :+1:

**Pull request merged**
